// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/bitdeer.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const BITDEER_MODELS: ChatModelCatalog<typeof values, "bitdeer"> =
	flattenChatModelCatalog("bitdeer", values);

export const BITDEER_IMAGE_MODELS: ImageModelCatalog<typeof values, "bitdeer"> =
	flattenImageModelCatalog("bitdeer", values);

export const BITDEER_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "bitdeer"> =
	flattenClassifierModelCatalog("bitdeer", values);
