// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/inco.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const INCO_MODELS: ChatModelCatalog<typeof values, "inco"> =
	flattenChatModelCatalog("inco", values);

export const INCO_IMAGE_MODELS: ImageModelCatalog<typeof values, "inco"> =
	flattenImageModelCatalog("inco", values);

export const INCO_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "inco"> =
	flattenClassifierModelCatalog("inco", values);
